---
# Role for doing the common setup work needed to install sensu
# on both a client and server
- name: Install Ruby Dependencies on RedHat
  yum: name={{ item }} state=present
  with_items:
    - rubygems
    - ruby-devel
    - gcc
  when: ansible_os_family == "RedHat"

- name: Install Ruby Dependencies on Debain
  apt: name={{ item }} state=present
  with_items:
    - rubygems
    - ruby-dev
    - gcc
  when: ansible_os_family == "Debian"

- name: Install EPEL on RedHat 6
  yum: name=http://mirror.pnl.gov/epel/6/i386/epel-release-6-8.noarch.rpm state=present
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 6 and ansible_lsb.major_release|int < 7

- name: Install EPEL on RedHat 7
  yum: name=http://mirror.pnl.gov/epel/7/x86_64/e/epel-release-7-2.noarch.rpmstate=present
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 7 and ansible_lsb.major_release|int < 8

# There is no sensu repo for EL7, but the internet has told me the packages for 6 stil work
- name: Install Sensu RedHat repo
  copy: src=roles/common/files/sensu.repo dest=/etc/yum.repos.d/sensu.repo
  when: ansible_os_family == "RedHat"

- name: Install Sensu apt key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present
  when: ansible_os_family == "Debian"

- name: Install Sensu Debian repo
  apt_repository: repo='deb http://repos.sensuapp.org/apt sensu main' state=present
  when: ansible_os_family == "Debian"

- name: Install/Update Debian Sensu
  apt: update_cache=yes name=sensu state=latest
  when: ansible_os_family == "Debian"

- name: Install/Update RedHat Sensu
  yum: name=sensu state=latest

- name: Install sensu-plugin gem
  gem: name=sensu-plugin state=latest user_install=false

- name: Install dummy config.json
  copy: src=roles/common/files/config.json dest=/etc/sensu/config.json
